[phases.setup]
nixPkgs = ['python3', 'gcc']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install hatchling build setuptools',
  '/opt/venv/bin/pip install -e ".[all]"'
]

[start]
cmd = 'PYTHONPATH=/app/src /opt/venv/bin/opencmo-web'
